version: "3"
services:
  myapp:
    image: nadagharbi/projet-devops
    ports:
      - 8086:8086
    depends_on:
      - mysqldb
    restart: always
  mysqldb:
    image: mysql
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_DATABASE: projetdevops
      MYSQL_USER: nada
      MYSQL_PASSWORD: nada
      MYSQL_ROOT_PASSWORD: nada
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql/data
volumes:
  db_data: {}
