version: "3"
services:
  springboot-image:
    image: nadagharbi/projet-devops
    container_name: projet-devops
    command: tail -F anything
    depends_on:
      - mysqldb
    ports:
      - 9001:9001
  mysqldb:
    image: mysql
    container_name: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: projetdevops
      MYSQL_USER: nada
      MYSQL_PASSWORD: nada
      MYSQL_ROOT_PASSWORD: nada