version: "3"
services:
  springboot-app:
    image: azzouzhanen2023/team1
    ports:
      - 8082:8082
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql
    ports:
      - 3307:3306
    restart: always
    environment:
      MYSQL_DATABASE: team1db
      MYSQL_USER: hanen
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root