version: "2"
services:
  springboot-app:
    image: azzouzhanen2023/team1
    ports:
      - 8082:8082
    depends_on:
      - mysqldb
    restart: always
  mysqldb:
    image: mysql
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_DATABASE: team1db
      MYSQL_USER: hanen
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql/data
volumes:
    db_data: {}