version: "3"
services:
  springboot-image:
    image: nadagharbi/projet-devops
    container_name: spring-container
    command: tail -F anything
    depends_on:
      - mysqldb
    ports:
      - 8086:8086
    restart: always
  mysqldb:
    image: mysql
    container_name: mysql-container
    ports:
      - 3307:3306
    restart: always
    environment:
      MYSQL_DATABASE: projetdevops
      MYSQL_USER: nada
      MYSQL_PASSWORD: nada
      MYSQL_ROOT_PASSWORD: nada
